package com.ecom.enums;

public enum Econfig {
	URL,
	BROWSER,
	OVERRIDE_REPORTS,
	PASSED_STEPSSCREENSHOTS,
	FAILED_STEPSSCREENSHOTS,
	SKIPPED_STEPSSCREENSHOTS,
	RETRY_FAILED_TESTS,
	CROSSBROWSER_TESTING,

}
